spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/caton?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: 123
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
